---
- name: Install dependencies
  apt:
    name: software-properties-common
    state: present
    install_recommends: no

#- name: add java PPA
#  apt_repository:
#    repo: 'ppa:webupd8team/java'
#    state: present
#  environment:
#    http_proxy: "{{ http_proxy | default('') }}"
#    https_proxy: "{{ https_proxy | default('') }}"

# Currently ansible doesn't support HTTPS proxy
- name: add java PPA
  apt_repository:
      repo: 'ppa:webupd8team/java'
#  command: "apt-add-repository -y ppa:webupd8team/java"
#  environment:
#    http_proxy: "{{ http_proxy | default('') }}"
#    https_proxy: "{{ https_proxy | default('') }}"

- name: accept oracle license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: install jdk
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: true
